### ISSUE TITLE
error in biz_server after registeration user

### ISSUE THREAD

**Issue by aliakbari** [nebulaim/telegramd#34]
after user register and login not contacts sync with server and give this error
`I0419 11:39:57.399750   50960 messages.readHistory_handler.go:39] MessagesReadHistory - metadata: {"server_id":1,"netlib_session_id":46,"client_addr":"192.168.3.135:26880","auth_id":6912075496930794124,"session_id":5778558658148480546,"trace_id":986864457563115521,"span_id":986864461770002432,"receive_time":1524121797,"user_id":8}, request: {"peer":{"constructor":2072935910,"data2":{"user_id":8,"access_hash":986836309442170880}},"max_id":-2147483648}
E0419 11:39:59.413989   50960 rpc_recovery_handler.go:32] BizUnaryRecoveryHandler - goroutine 2809 [running]:
runtime/debug.Stack(0xc04280b478, 0x42b67f, 0x410b41)
        C:/Go/src/runtime/debug/stack.go:24 +0xae
github.com/nebulaim/telegramd/grpc_util.BizUnaryRecoveryHandler(0x1aac1c0, 0xc0424a6ff0, 0x101bba0, 0x1b24210, 0x0, 0x0)
        D:/Programming/Source/WHC/Go/src/github.com/nebulaim/telegramd/grpc_util/rpc_recovery_handler.go:32 +0x3b
github.com/nebulaim/telegramd/grpc_util/middleware/recovery2.unaryRecoverFrom(0x1aac1c0, 0xc0424a6ff0, 0x101bba0, 0x1b24210, 0x12042c8, 0x0, 0x0)
        D:/Programming/Source/WHC/Go/src/github.com/nebulaim/telegramd/grpc_util/middleware/recovery2/interceptors.go:75 +0x61
github.com/nebulaim/telegramd/grpc_util/middleware/recovery2.UnaryServerInterceptor.func1.1(0xc04280b978, 0x1aac1c0, 0xc0424a6ff0, 0xc0422b26c0)
        D:/Programming/Source/WHC/Go/src/github.com/nebulaim/telegramd/grpc_util/middleware/recovery2/interceptors.go:42 +0x7e
panic(0x101bba0, 0x1b24210)
        C:/Go/src/runtime/panic.go:491 +0x291
github.com/nebulaim/telegramd/biz_server/messages/rpc.(*MessagesServiceImpl).MessagesReadHistory(0x1b59dc8, 0x1aac1c0, 0xc0424a6ff0, 0xc0424a5250, 0x1b59dc8, 0xc04280b8d8, 0x1)
        D:/Programming/Source/WHC/Go/src/github.com/nebulaim/telegramd/biz_server/messages/rpc/messages.readHistory_handler.go:98 +0x8f4
github.com/nebulaim/telegramd/mtproto._RPCMessages_MessagesReadHistory_Handler.func1(0x1aac1c0, 0xc0424a6ff0, 0x10e5900, 0xc0424a5250, 0xc0424a6ff0, 0xc0422b26c0, 0x4112cf, 0x20)
        D:/Programming/Source/WHC/Go/src/github.com/nebulaim/telegramd/mtproto/schema.tl.sync_service.pb.go:13418 +0x90
github.com/nebulaim/telegramd/grpc_util/middleware/recovery2.UnaryServerInterceptor.func1(0x1aac1c0, 0xc0424a6ff0, 0x10e5900, 0xc0424a5250, 0xc04263c6a0, 0xc04263c6c0, 0x0, 0x0, 0x0, 0x0)
        D:/Programming/Source/WHC/Go/src/github.com/nebulaim/telegramd/grpc_util/middleware/recovery2/interceptors.go:47 +0xde
github.com/nebulaim/telegramd/mtproto._RPCMessages_MessagesReadHistory_Handler(0x11ac0a0, 0x1b59dc8, 0x1aac1c0, 0xc0424a6ff0, 0xc04293e310, 0xc042315260, 0x0, 0x0, 0xc0421f2660, 0xc0421f2680)
        D:/Programming/Source/WHC/Go/src/github.com/nebulaim/telegramd/mtproto/schema.tl.sync_service.pb.go:13420 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0xc04245c900, 0x1ab02a0, 0xc042456900, 0xc0428e40f0, 0xc0426b4840, 0x1b344a0, 0x0, 0x0, 0x0)
        D:/Programming/Source/WHC/Go/src/google.golang.org/grpc/server.go:969 +0x934
google.golang.org/grpc.(*Server).handleStream(0xc04245c900, 0x1ab02a0, 0xc042456900, 0xc0428e40f0, 0x0)
        D:/Programming/Source/WHC/Go/src/google.golang.org/grpc/server.go:1194 +0x152f
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc042536180, 0xc04245c900, 0x1ab02a0, 0xc042456900, 0xc0428e40f0)
        D:/Programming/Source/WHC/Go/src/google.golang.org/grpc/server.go:677 +0xa6
created by google.golang.org/grpc.(*Server).serveStreams.func1
        D:/Programming/Source/WHC/Go/src/google.golang.org/grpc/server.go:675 +0xa8
E0419 11:39:59.413989   50960 rpc_recovery_handler.go:44] Panic: rpc error: code = Unknown desc = panic unknown triggered: runtime error: invalid memory address or nil pointer dereference`

**Comment by wubenqi** [comment]
1. Delete dirty data in the table `user_dialogs`
    delete user_dialogs where user_id=8 and peer_type=1
2. git pull
3. restart biz_server.
