### ISSUE TITLE
session run error http: multiple registrations for /debug/requests

### ISSUE THREAD

**Issue by vchakoshy** [nebulaim/telegramd#47]
~$ go run session.go 
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x18547e0, 0xfbe066, 0xf, 0x179ee00, 0xffdd08)
	/usr/local/go/src/net/http/server.go:2270 +0x627
net/http.(*ServeMux).HandleFunc(0x18547e0, 0xfbe066, 0xf, 0xffdd08)
	/usr/local/go/src/net/http/server.go:2302 +0x55
net/http.HandleFunc(0xfbe066, 0xf, 0xffdd08)
	/usr/local/go/src/net/http/server.go:2314 +0x4b
github.com/coreos/etcd/vendor/golang.org/x/net/trace.init.0()
	/home/vahid/go/src/github.com/coreos/etcd/vendor/golang.org/x/net/trace/trace.go:115 +0x42
github.com/coreos/etcd/vendor/golang.org/x/net/trace.init()
	<autogenerated>:1 +0x1cd
github.com/coreos/etcd/vendor/google.golang.org/grpc.init()
	<autogenerated>:1 +0x96
github.com/coreos/etcd/etcdserver/etcdserverpb.init()
	<autogenerated>:1 +0x87
github.com/coreos/etcd/clientv3.init()
	<autogenerated>:1 +0x5f
github.com/nebulaim/telegramd/baselib/grpc_util.init()
	<autogenerated>:1 +0x89
github.com/nebulaim/telegramd/access/session/server.init()
	<autogenerated>:1 +0xaf
main.init()
	<autogenerated>:1 +0x4e
exit status 2

**Comment by vchakoshy** [comment]
rm -rf $GOPATH/src/github.com/coreos/etcd/vendor/golang.org/x/net/trace
see https://github.com/coreos/etcd/issues/9357#issuecomment-377560659
