### ISSUE TITLE
panic: http: multiple registrations for /debug/requests

### ISSUE THREAD

**Issue by abugandar** [nebulaim/telegramd#81]
how to fix tis error
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x177fa80, 0xf7f4a6, 0xf, 0x16f1900, 0xfb8dd8)
        /usr/local/go/src/net/http/server.go:2270 +0x627
net/http.(*ServeMux).HandleFunc(0x177fa80, 0xf7f4a6, 0xf, 0xfb8dd8)
        /usr/local/go/src/net/http/server.go:2302 +0x55
net/http.HandleFunc(0xf7f4a6, 0xf, 0xfb8dd8)
        /usr/local/go/src/net/http/server.go:2314 +0x4b
github.com/coreos/etcd/vendor/golang.org/x/net/trace.init.0()
        /root/work/src/github.com/coreos/etcd/vendor/golang.org/x/net/trace/trace.go:115 +0x42
github.com/coreos/etcd/vendor/golang.org/x/net/trace.init()
        <autogenerated>:1 +0x1cd
github.com/coreos/etcd/vendor/google.golang.org/grpc.init()
        <autogenerated>:1 +0x96
github.com/coreos/etcd/etcdserver/etcdserverpb.init()
        <autogenerated>:1 +0x87
github.com/coreos/etcd/clientv3.init()
        <autogenerated>:1 +0x5f
github.com/nebulaim/telegramd/baselib/net2/watcher2.init()
        <autogenerated>:1 +0x44
github.com/nebulaim/telegramd/access/frontend/server.init()
        <autogenerated>:1 +0x7f
main.init()
        <autogenerated>:1 +0x49

Wich go version we need to use ??
i am using go version go1.9.1 linux/amd64

**Comment by wubenqi** [comment]
# notes
* if a panic is raised for http: multiple registrations for /debug/requests then 
[remove github.com/coreos/etcd/vendor/golang.org/x/net/trace folder](https://github.com/coreos/etcd/issues/9357)
