### ISSUE TITLE
Frontend error

### ISSUE THREAD

**Issue by Koristo** [nebulaim/telegramd#96]
Hello. I try connect to server with https://github.com/zhukov/webogram (port 8080). When I did it, here's no connection and error in frontend, logs:
`goroutine 103 [running]:
runtime/debug.Stack(0xc42049fd50, 0xd40120, 0x16763e0)
	/usr/lib/go-1.10/src/runtime/debug/stack.go:24 +0xa7
github.com/nebulaim/telegramd/baselib/net2.(*TcpServer).establishTcpConnection.func1(0xc4202a0780)
	/home/git/Programms/src/github.com/nebulaim/telegramd/baselib/net2/tcp_server.go:180 +0x5a
panic(0xd40120, 0x16763e0)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
encoding/binary.binary.littleEndian.Uint64(...)
	/usr/lib/go-1.10/src/encoding/binary/binary.go:76
github.com/nebulaim/telegramd/mtproto.(*MTProtoHttpProxyCodec).Receive(0xc4203f2140, 0xc42049ff00, 0x429fd9, 0x8, 0xc4203fe380)
	/home/git/Programms/src/github.com/nebulaim/telegramd/mtproto/mtproto_http_proxy_codec.go:53 +0x1d9
github.com/nebulaim/telegramd/mtproto.(*MTProtoProxyCodec).Receive(0xc4200dccc0, 0xf032a8, 0xc4202a07c0, 0xdb3d80, 0xc4200dcd00)
	/home/git/Programms/src/github.com/nebulaim/telegramd/mtproto/mtproto_proxy_codec.go:327 +0x3d
github.com/nebulaim/telegramd/baselib/net2.(*TcpConnection).Receive(0xc4202a0780, 0x0, 0x0, 0x0, 0x0)
	/home/git/Programms/src/github.com/nebulaim/telegramd/baselib/net2/tcp_connection.go:128 +0x88
github.com/nebulaim/telegramd/baselib/net2.(*TcpServer).establishTcpConnection(0xc4200e84d0, 0xc4202a0780)
	/home/git/Programms/src/github.com/nebulaim/telegramd/baselib/net2/tcp_server.go:188 +0x71
created by github.com/nebulaim/telegramd/baselib/net2.(*TcpServer).Serve2
	/home/git/Programms/src/github.com/nebulaim/telegramd/baselib/net2/tcp_server.go:128 +0xed
I0709 12:24:57.664750   22866 server.go:318] onConnectionClosed - peer({connID: 22, name: frontend80, lAddr: [::1]:8000, rAddr: [::1]:56184})
`

**Comment by wubenqi** [comment]
Sorry, webogram support has not yet been tested.
